# -*- coding: utf-8 -*-
"""10.3.Tensorflow.Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcPr7nZB7WGihzyIe41YMSkqBbTA_U3r
"""

import tensorflow as tf
scalar=tf.constant(10)
print(f"scalar value:{scalar.numpy()}, datatype is:{scalar.dtype}")

vector=tf.constant([10,20,30])
print(f"vector value:{vector.numpy()} shape:{vector.shape}")

matrix=tf.constant([[1,2],[3,4]])
print(f"matrix value:{matrix.numpy()}, shape:{matrix.shape}, data type:{matrix.dtype} ")

variable=tf.Variable(5)
print(variable.numpy())

updated_var=variable.assign(10)
print(updated_var.numpy())
print(variable.numpy())

var1=tf.Variable([[1.0,2.0],[3.0,4.0]])
var1.assign_add([[1.0,1.0],[1.0,1.0]])
print(var1.numpy())

a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])
tf.matmul(a,b).numpy()

a=tf.random.uniform((3,3))
print(f"value is {a.numpy} data type is {a.dtype}, shape is {a.shape}")