# -*- coding: utf-8 -*-
"""9.3.MatPlotLib.Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypQDfAaL20ZfLBXznc6Pq2MRoFaGHfwB
"""

# Q1: Create a simple line plot of y = 2x + 3 for x values ranging from 0 to 10.
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = 2 * x + 3
plt.plot(x,y)
plt.title("line plot graph")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

# Q2: Plot sin(x) and cos(x) on the same graph with different colors, line styles, and labels, and display a legend.
x=np.linspace(0,10,100)
y1=np.sin(x)
y2=np.cos(x)
plt.plot(x,y1,label="sin(x)",color="red",linestyle="--")
plt.plot(x,y2,label="cos(x)",color="blue",linestyle="-")
plt.legend()

plt.title("sin(x) and cos(x) graph")

# Q3: Create a bar chart showing the sales of four products: A, B, C, and D with random values.
x=["A","B","C","D"]
y=np.random.randint(1,10,4)
plt.bar(x,y,color="orange")
plt.title("bar chart for products")

# Q4: Generate a scatter plot with random x and y values between 0 and 1, and use different colors for points.
x=np.random.rand(100)
y=np.random.rand(100)
colors=100 * np.random.rand(100)
plt.scatter(x,y,c=colors,alpha=0.5,cmap="viridis")
plt.title("scatter plot")

# Q5: Plot a histogram for 1000 random numbers generated from a normal distribution.
x=np.random.rand(1000)
plt.hist(x,bins=20,color="green",edgecolor="red")
plt.title("histogram")

# Q6: Draw a pie chart representing the percentage of five fruits: Apple, Banana, Mango, Grapes, and Orange.
fruits=["apple","banana","mango","grapes","orange"]
percent=[20,30,10,25,15]
plt.pie(percent,labels=fruits,autopct="%1.1f%%")
plt.title("pie chart")

# Q7: Create two subplots in one figure – one showing a sine wave and the other showing a cosine wave.
x=np.linspace(0,10,100)
y1=np.sin(x)
y2=np.cos(x)
plt.figure(figsize=(10,5))

plt.subplot(1,2,2)
plt.plot(x,y2)
plt.title("cosine wave")

plt.subplot(1,2,1)
plt.plot(x,y1)
plt.title("sine wave")

# Q8: Customize a line plot by adding title, axis labels, grid lines, and saving it as 'line_plot.png'.
x=np.linspace(0,10,100)
y=2*x+3
plt.plot(x,y)
plt.title("line plot")
plt.xlabel("x")
plt.ylabel("y")
plt.grid(True)
plt.savefig("line_plot.png")

# Q9: Create a 2x2 grid of subplots showing different plots: line, bar, scatter, and histogram.
fig,axs=plt.subplots(2,2)
axs[0,0].plot(x,y)
axs[0,1].bar(x,y)
axs[1,0].scatter(x,y)
axs[1,1].hist(x,bins=20)
plt.tight_layout()
plt.suptitle("subplots")

# Q10: Create a line plot for y = e^x for x between 0 and 5, and change the color, marker, and line style.
x=np.linspace(0,5,100)
y=np.exp(x)
plt.plot(x,y,color="red",marker="x",linestyle="--")