# -*- coding: utf-8 -*-
"""3.4.CASE_STUDY1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-Bk1afgUYDjnl0WlGMs7A2BhwoTd_QM
"""

#case study A: employee skills
employee_data={}
n=int(input("enter number of employees:"))
for i in range(n):
    name=input("name of employee:")
    skills=input("skills of employee").split(",")
    employee_data[name]=skills

print("employees with python and sql:")
for name,skills in employee_data.items():
    if "python" in skills and "sql" in skills:
        print("name:",name)


all_skills=set()
for s in employee_data.values():
    all_skills.update(s)
print("all unique skills:",all_skills)

target=input("enetr name to check shared skills:")
if target in employee_data:
    target_skills=employee_data[target]
    print(f"people who shared atleast one skill with {target}:")
    for name,skills in employee_data.items():
        if name!=target:
            common=target_skills & skills
            if len(common)>0:
                print(name,":",common)
            else:
                print("employee not found")

#Case study B:Product inventory analyser
warehouse1={}
warehouse2={}
n1=int(input("how many products in warehouse 1?"))
for i in range(n1):
    pname=input("product name:").strip()
    qty=int(input("quantity"))
    warehouse1[name]=qty

n2=int(input("how many products in warehouse 2?"))
for i in range(n2):
    pname=input("product name:")
    qty=int(input("Quantity:"))
    warehouse2[pname]=qty

common_pnames=set(warehouse1.keys()) & set(warehouse2.keys())
print("All common product names: ",common_pnames)

unique_names=set(warehouse1.keys()) | set(warehouse2.keys())
print("all unique products from both warehouses:",unique_names)

combined_inventory=[]
for pname, qty in warehouse1.items():
    combined_inventory.append({"name":pname,"qty":qty})
for pname, qty in warehouse2.items():
    combined_inventory.append({"name":pname,"qty":qty})
sorted_inventory=sorted(combined_inventory,key=lambda x:x["qty"],reverse=True)
print("combined inventory:",combined_inventory)

#Case C: University course Registration system
registrations=[]
n=int(input("enter number of registrations:"))
for i in range(n):
    name=input("enter student name")
    course=input("enter course name:")
    registrations.append((name,course))

#case D: customer purchase insights

purchase_data = []
n = int(input("enter number of customers: "))

for i in range(n):
    name = input("enter customer name")
    products = input("enter products bought").split(",")

    purchase_data.append((name, products))
all_products = set()
for name, products in purchase_data:
    all_products.update(products)

print("total unique products bought:", len(all_products)")

print("customers who bought both laptop and headphones:")
for name, products in purchase_data:
    if "laptop" in products and "headphones" in products:
    print("customer with both laptop and headphones is",name)

product_counts = {}
for name, products in purchase_data:

#Case E: travel planner

bookings = []
n = int(input("how many booking entries to enter? "))
for i in range(n):
    name = input("traveler name: ").strip()
    dest = input("destination: ").strip()
    date = input("date: ").strip()
    bookings.append((name, dest, date))

unique_bookings = set(bookings)

print("total bookings:", len(bookings))
print("unique bookings after deduplication:", len(unique_bookings)")

#Case f: Student attendance analyzer
attendance_days = []

for i in range(1, 6):
    names = input("enter students name")
    day_set = input("enter p or a").strip().split(",")
    attendance_days.append((names, day_set))
    count=0
for i in day_set:
  if (i=="p"):
    pcount=pcount+1
    if(pcount>=6):
      print(f"{names} is present everyday")
      break;