# -*- coding: utf-8 -*-
"""4.2.dictionary_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCipGY8NX8d-U8vln7xSarJsu60cwMUT
"""

# Create a dictionary with 5 students and their marks.
# Print the value of a specific student using their name as the key.
# Add a new student with marks to the dictionary.
# Update the marks of an existing student.
# Delete a student from the dictionary.
# Print all student names using keys().
# Print all student marks using values().
# Print all student names with their marks using items().
# Check for existence: Verify if a specific student is in the dictionary and check if a specific mark is present in the values.
# Safe fetching: Use get() to fetch a student's marks safely.
# Conditionals: Count how many students scored above 80 marks.
# Create a dictionary of employees with their departments.
# Access the department of a specific employee.
# Add a new employee and their department.
# Change the department of an existing employee.
# Remove an employee from the dictionary.
# Sorting & Data Manipulation
# Sort by Names: Sort the employee dictionary by names in ascending and descending order.
# Sort by Departments: Sort the employee dictionary by department names in ascending and descending order.
# Reverse Search: Find all keys that have a specific value in a dictionary.
# Dictionary Operations: Merge two student dictionaries into one , clear all entries , and copy/modify a dictionary.
# Dictionary Comprehension/Creation: Create a dictionary where keys are numbers 1-5 and values are their squares.
# Structure: Create a nested dictionary for 3 students including age, grade, and department.
# Access: Access the grade of a student from the nested structure.
# Update: Update the department of a student in the nested dictionary.
# Iteration: Loop through the nested dictionary and print student names with their grades.

# Create a dictionary with 5 students and their marks.
stud_dict={"raj":50,"ram":25,"mohan":36,"raju":74,"rama":73}
print(stud_dict)

# Print the value of a specific student using their name as the key.
print(stud_dict["raj"])
print(stud_dict["ram"])
print(stud_dict["mohan"])
print(stud_dict["raju"])
print(stud_dict["rama"])

# Add a new student with marks to the dictionary.
stud_dict["ravi"]=67
print(stud_dict)

# Update the marks of an existing student.
stud_dict["ravi"]=68
print(stud_dict)

# Delete a student from the dictionary.
del stud_dict["ravi"]
print(stud_dict)

# Print all student names using keys().
print(stud_dict.keys())

# Print all student marks using values().
print(stud_dict.values())

# Print all student names with their marks using items().
print(stud_dict.items())

# Check for existence: Verify if a specific student is in the dictionary and check if a specific mark is present in the values.
print("raj" in stud_dict)
print(50 in stud_dict.values())

# Safe fetching: Use get() to fetch a student's marks safely.
print(stud_dict.get("raj"))

# Conditionals: Count how many students scored above 80 marks.
count = 0
for i in stud_dict.values():
    if i > 80:
        count = 1+count
print(f"Number of students scoring above 80: {count}")

# Create a dictionary of employees with their departments.
emp_dep={"raj":"IT","ram":"HR","mohan":"IT"}
print(emp_dep)

# Access the department of a specific employee.
print(emp_dep["mohan"])

# Add a new employee and their department.
emp_dep["raja"]="cs"
print(emp_dep)

# Change the department of an existing employee.
emp_dep["raja"]="IT"
print(emp_dep)

# Remove an employee from the dictionary.
del emp_dep["raja"]
print(emp_dep)

# Sort by Names: Sort the employee dictionary by names in ascending and descending order.
print(sorted(emp_dep.keys()))
print(sorted(emp_dep.keys(),reverse=True))

# Sort by Departments: Sort the employee dictionary by department names in ascending and descending order.
print(sorted(emp_dep.values()))
print(sorted(emp_dep.values(),reverse=True))

# Reverse Search: Find all keys that have a specific value in a dictionary.
data = {"Alice": "A", "Bob": "B", "Charlie": "A", "David": "C"}
target_value = "A"
for key,value in data.items():
    if value==target_value:
        print(key)

# Dictionary Operations: Merge two student dictionaries into one , clear all entries , and copy/modify a dictionary.
dict1 = {"Alice": 85, "Bob": 78}
dict2 = {"Charlie": 92, "David": 65}
dict1.update(dict2)
print(dict1)

original_dict= {"Alice": 85, "Bob": 78}
original_dict.clear()
print(original_dict)

# Dictionary Comprehension/Creation: Create a dictionary where keys are numbers 1-5 and values are their squares.
square={x:x**2 for x in range(1,6)}
print(square)

# Structure: Create a nested dictionary for 3 students including age, grade, and department.
nested_disct={"alice":{"age":20,"grade":"A","department":"computer science"},
              "bob":{"age":21,"grade":"B","department":"ME"},
              "Charlie":{"age":22,"grade":"C","department":"IT"}}
print(nested_disct)

# Access: Access the grade of a student from the nested structure.
print(nested_disct["alice"]["grade"])

# Update: Update the department of a student in the nested dictionary.
nested_disct["alice"]["department"]="IT"
print(nested_disct)

# Iteration: Loop through the nested dictionary and print student names with their grades.
for name,details in nested_disct.items():
  grade=details["grade"]
  print(name,grade)