# -*- coding: utf-8 -*-
"""5.3.LOOPS_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBVlQ0S960Ti3rabMLLRciUaX8VEat2F
"""

# While Loop:

# 1. Write a program using while loop to print numbers from 1 to 10.
# 2. Use while loop to print even numbers between 1 and 50.
# 3. Write a while loop to calculate the sum of first 20 natural numbers.
# 4. Create a program using while loop to print multiplication table of 7.
# 5. Write a program to reverse a given number using while loop.
# 6. Use while loop to count the number of digits in an integer entered by the user.
# 7. Write a program to print factorial of a number using while loop.
# 8. Write a program using while loop to print the Fibonacci sequence up to 50.
# 9. Write a program to check whether a given number is a palindrome using while loop.
# 10. Write a while loop that continues taking input until the user enters 'exit'.


# Do While Loop

# 1. Simulate a do-while loop to print numbers from 1 to 10.
# 2. Simulate a do-while loop to take user input until a positive number is entered.
# 3. Use a do-while structure to display a menu until the user selects "Quit".
# 4. Simulate do-while loop to print the multiplication table of 19.
# 5. Create a do-while simulation that keeps asking for a password until it matches.
# 6. Simulate do-while to find the sum of digits of a number entered by user.
# 7. Simulate a do-while loop to print numbers from 10 down to 1.
# 8. Simulate do-while loop to check whether the entered number is prime or not.
# 9. Simulate do-while loop to print all odd numbers between 1 and 30.
# 10. Simulate do-while loop to calculate the product of numbers until user enters 0.


# For Loop

# 1. Write a for loop to print numbers from 1 to 20.
# 2. Write a for loop to print the square of numbers from 1 to 10.
# 3. Use for loop to display even numbers from 2 to 40.
# 4. Write a for loop to print the multiplication table of 12.
# 5. Create a for loop to calculate factorial of a given number.
# 6. Write a for loop to print elements of a list containing 10 integers.
# 7. Write a for loop to count how many vowels are in a given string.
# 8. Use nested for loop to print a right-angled triangle pattern of stars (*).
# 9. Use for loop to print numbers from 100 down to 1 in reverse order.
# 10. Write a for loop to display only odd numbers from 1 to 25 and calculate their sum.

# 1. Write a program using while loop to print numbers from 1 to 10.
i=1
while(i<=10):
  print(i)
  i=i+1

# 2. Use while loop to print even numbers between 1 and 50.
i=1
while(i<=50):
  if (i%2==0):
    print(i)
    i=i+1

# 3. Write a while loop to calculate the sum of first 20 natural numbers.
i=1
sum=0
while(i<=20):
  sum=sum+i

  i=i+1
print(sum)

# 4. Create a program using while loop to print multiplication table of 7.
i=1
while(i<=10):
  print(f"7 * {i} = {7*i}")
  i=i+1

# 5. Write a program to reverse a given number using while loop.
num=int(input("Enter a number: "))
rev=0
while num>0:
  rem=num%10
  rev=rev*10+rem
  num=num//10
print(rev)

# 6. Use while loop to count the number of digits in an integer entered by the user.
user_input=int(input("Enter a number: "))
count=0
while user_input>0:
  user_input=user_input//10
  count=count+1
print(count)

# 7. Write a program to print factorial of a number using while loop.
num=int(input("Enter a number: "))
fact=1
a=1
while num>0:
  fact=fact*a
  a=a+1
print(fact)

# 8. Write a program using while loop to print the Fibonacci sequence up to 50.
num=int(input("enter number"))
a=0
b =1
while a<= num:
    print(a)
    a = b
    b=a + b

# 9. Write a program to check whether a given number is a palindrome using while loop.

# 10. Write a while loop that continues taking input until the user enters 'exit'.

while True:
  num=input("enter anything")

  if num=="exit":
    break

# 1. Simulate a do-while loop to print numbers from 1 to 10.
i=1
while True:
  print(i)
  i=i+1
  if i>10:
    break

# 2. Simulate a do-while loop to take user input until a positive number is entered.
while True:
  num=int(input("enter number"))
  if num>0:
    break

# 3. Use a do-while structure to display a menu until the user selects "Quit".
while True:
  print("1. Start")
  print("2. Something")
  print("3. Quit")
  choice=int(input("enter choice"))
  if choice==3 or choice=="quit":
    break

# 4. Simulate do-while loop to print the multiplication table of 19.
i=1
while True:
  print(f"19 * {i}={19*i}")
  i=i+1
  if i>10:
    break

# 5. Create a do-while simulation that keeps asking for a password until it matches.
correctp="1234"
while True:
  pw=input("enter password")
  if pw==correctp:
    print("welcome. access granted")
    break

# 6. Simulate do-while to find the sum of digits of a number entered by user.
num=int(input("enter number"))
sum=0
while True:
  rem=num%10
  sum=sum+rem
  num=num//10
print(sum)

# 7. Simulate a do-while loop to print numbers from 10 down to 1.
i=10
while True:
  print(i)
  i=i-1
  if i<1:
    break

# 8. Simulate do-while loop to check whether the entered number is prime or not.
num=int(input("enter number"))
i=2
while True:
  if num==2:
    print("prime number")
  elif num%i!=0:
    print("prime number")
    i=i+1
  else:
    print("not a prime number")

  if i>num:
    break

# 9. Simulate do-while loop to print all odd numbers between 1 and 30.

i=1
while True:
  if i%2!=0:
    print(i)
    i=i+1
  if i>30:
    break

# 10. Simulate do-while loop to calculate the product of numbers until user enters 0.
prod=1
while True:
  num=int(input("enter number"))
  if num==0:
   break
  prod=prod*num
  print(prod)

# 1. Write a for loop to print numbers from 1 to 20.
i=1
for i in range(1,21):
  print(i)
  i=i+1

# 2. Write a for loop to print the square of numbers from 1 to 10.
i=1
for i in range (1,11):
  print(i**2)

# 3. Use for loop to display even numbers from 2 to 40.
for i in range(2,41):
  if i%2==0:
    print(i)

# 4. Write a for loop to print the multiplication table of 12.
for i in range(1,11):
  print(f"12 * {i} = {12*i}")
  i=i+1

# 5. Create a for loop to calculate factorial of a given number.
num=int(input("enter number"))
fact=1
for i in range(1,num+1):
  fact=fact*i
  i=i+1
  print(fact)

# 6. Write a for loop to print elements of a list containing 10 integers.
list=[1,2,3,4,5,6,7,8,9,10]
for i in list:
  print(i)

# 7. Write a for loop to count how many vowels are in a given string.
count=0
str=input("enter string")
for i in str:
  if i=="a" or i=="e" or i=="i" or i=="o" or i=="u":
    count=count+1
print(count)

# 8. Use nested for loop to print a right-angled triangle pattern of stars (*).
n=5
for i in range(1,n+1):
  for j in range(i):
    print("*",end="")
  print()

# 9. Use for loop to print numbers from 100 down to 1 in reverse order.
n=100
for i in range(n,0,-1):
  print(i)

# 10. Write a for loop to display only odd numbers from 1 to 25 and calculate their sum.
sum=0
for i in range(1,26):
  if i%2!=0:
    sum=sum+i
    print(f"sum upto {i} is {sum}")