# -*- coding: utf-8 -*-
"""6.3.Variable-NestedFunction.Assignement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bv1u0hFSvVLOY72JeGOPoHvmj25vsptb
"""

# 1 Write a program to demonstrate how a local variable inside a function works and is not accessible outside the function
def fun():
  num=1
  print("defined inside function",num)
fun()
print("outside the function",num)

# 2 Subtotal: 2420
 # Tax: 121.0
 # Discount: 242.0
 # Total: 2299.0
 # Payment: UPI Create a function that defines a global variable inside it using the global keyword and modify its value

tax=121
discount=242
total=2299
payment="upi"
def fun():
  global tax
  global total
  global payment
  global discount
  tax=300
  discount=300
  total=3000
  payment="cash"
  print("inner",tax,total,payment,discount)
fun()
print("outer",tax,total,payment,discount)

# 3 Write a program where a global variable is updated by multiple function calls using the global keyword
tax=121
def fun():
    global tax
    tax=tax+100
    print("inner",tax)
fun()
fun()
fun()
print("outer",tax)

# 4 Create two functions where both use a global variable to calculate and store cumulative total sales
total_sales=100
def fun1():
    global total_sales
    total_sales=total_sales+100
    print("fun1 total sales",total_sales)


def fun2():
    global total_sales
    total_sales=total_sales+100
    print("fun2 total sales",total_sales)
fun1()
fun2()

# 5 Write a nested function where the inner function accesses an enclosing variable from the outer function
def outer():
  x=100
  print("outer 100",x)
  def inner():
    nonlocal x
    print("inner 100",x)
  inner()
outer()

# 6 Demonstrate the use of nonlocal keyword by modifying an enclosing variable inside an inner function
def outer():
  x=100
  print("outer 100",x)
  def inner():
    nonlocal x
    x=x+100
    print("inner 100 modified",x)
  inner()
outer()

# 7 Create a nested function structure with three levels and print variables from local enclosing and global scopes
x="global"
def fun1():
  x="enclosing"
  def fun2():
    x="local"
    print("fun2 local x",x)
  fun2()
  print("fun1 enclosing x",x)
fun1()
print("global x",x)

# 8 Write a function where local variable shadows a global variable and show both outputs
x=100
def glob():
  print(x)
  def inner():
    x=200
    print(x)
  inner()
print(x)
glob()

# 9 Create a program to show how Python searches variable names using the LEGB rule
x="global"
def fun1():
  x="enclosing"
  def fun2():
    x="local"
    print("fun2 local x",x)
  fun2()
  print("fun1 enclosing x",x)
fun1()
print("global x",x)

# 10 Write a function to show that local variables are destroyed after function execution ends
def fun():
  x=100
  print(x)
fun()
print(x)

# 11 Create a nested function where both inner and outer functions take arguments and print their values
def outer(x):
  print("outer x",x)
  def inner(y):
    print("inner y",y)
  inner(10)
  print("outer x",x)
outer(20)

# 12 Write a nested function that calculates total marks using an outer function for input and an inner function for computation
def outer():
  marks=int(input("enter marks"))
  def inner():
    total=marks+10
    print("total marks",total)
  inner()
outer()

# 13 Demonstrate how enclosing variable stores the running total for a counter function using nonlocal
def fun1():
  count=0
  def increment():
    nonlocal count
    count=count+1
    print("count",count)
  increment()
fun1()
fun1()

# 14 Write a closure function that generates a multiplier and demonstrate how the enclosing variable remembers state
def fun1(a):
  def fun2(b):
    return a*b
  return fun2
fun3=fun1(10)
print(fun3(2))

# 15 Create a function with variable positional arguments to calculate the sum of all given numbers
def fun1(*args):
  return sum(args)
print(fun1(10,29,30))

# 16 Write a function with variable positional arguments that finds the maximum value from all numbers passed
def fun1(*num):
  return max(num)
print(fun1(8,37,33,38,39))

# 17 Create a function with variable keyword arguments that displays student details such as name age and grade
def student_details(**kwargs):
  for key,value in kwargs.items():
    print(key,value)

student_details(name="ram",age=20,grade="A")

# 18 Write a function using variable keyword arguments to print employee records with department and salary
def employee_records(**kwargs):
  for key,value in kwargs.items():
    print(key,value)
employee_records(deptartment="ai",salary=10000)

# 19 Combine *args and **kwargs in a single function and print both values separately
def fun2(*args,**kwargs):
  print(args)
  print(kwargs)
fun2(10,20,30,40,name="ram",age=20)

# 20 Write a function that uses *args to calculate average sales for any number of branches
def avg_sales(*args):
  return sum(args)/len(args)

print(avg_sales(10,20,30,40,50))

# 21 Write a function that uses **kwargs to configure a model where parameters like learning_rate and epochs are passed dynamically
def fun1(**kwargs):
  for key,value in kwargs.items():
    print(key,value)
fun1(learning_rate=20.00,epochs=50)

# 22 Create a nested function that uses *args in the inner function to calculate the total of passed values
def outer():
  def inner(*args):
    print(sum(args))
  inner(10,20,30)
outer()

# 23 Write a program where an outer function accepts employee details and inner function calculates bonus based on salary
def employee(name,salary):
  def calculate():
    if salary>=10000:
      return salary*0.20
    elif salary>=5000:
      return salary*0.50
      print(name,salary)
  calculate()
employee("ram",10000)

# 24 Demonstrate how a nonlocal variable can be used to maintain the count of how many times a nested function has been called
def fun():
  count=0
  def inner():
    nonlocal count
    count=count+1
    print(count)
  inner()
fun()
fun()
fun()

# 25 Write a program to show how global and local variables can have the same name but store different data
a="global"
def fun():
  a="local"
  print("local",a)
fun()
print("global",a)

# 26 Create a nested function example where inner function modifies enclosing variable to accumulate running total of expenses
def fun4():
  total=0
  def fun5():
    nonlocal total
    total=total+100
    print(total)
  return fun5()
fun4()

# 27 Write a function that uses *args to concatenate multiple strings into a single string
def join_str(*args):
  return"" .join(args)
print(join_str("i ","am ","rutu"))

# 28 Create a function that uses **kwargs to print formatted key value pairs as system configuration parameters
def config(**kwargs):
  for key,value in kwargs.items():
    print(key,value)
config(cpu="4",port=4)

# 29 Write a function with both *args and **kwargs to simulate order details containing items and their prices
def order_details(*items,**prices):
  print("order details")
  print("name of items",items)
  for name,price in prices.items():
    print(name,price)
    total=total+price
  print("total bill",total)
order_details("pen","pencil",pen=10,pencil=5)

# 30 Design a nested function where the outer function provides base salary and the inner function adds incentives using nonlocal variable
def salary(base):
  incentive=0
  def increment(n):
    nonlocal incentive
    incentive=incentive+n
    return base+incentive
  return increment
b=salary(5000)
b(500)