# -*- coding: utf-8 -*-
"""8.3.Pandas_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwApNvmeUpbvkvSJXrnaL3oYGzS3L_xR
"""

# Create a Pandas Series using a list of 5 random numbers and custom index names; print the series and its data type.
import pandas as pd
import numpy as np
import random
series=pd.Series(np.random.randint(1,10), index=['a','b','c','d','e'])
print(series)
print(series.dtype)

# Create a DataFrame with columns "Student_Name", "Maths", "Science", and "English"; fill it with 5 sample records and display the top 3 rows using head().
student={
    "student_name":["A","B","C","D","E"],
    "maths":[10,20,30,40,50],
    "science":[93,37,47,48,95],
    "english":[67,83,52,57,83]
}
df=pd.DataFrame(student)
print(df.head(3))

# Import a CSV file into a DataFrame; display the number of rows and columns using shape, and print the column names.
df.to_csv("student.csv")
df=pd.read_csv("student.csv")
print(df.shape)
print(df.columns)
# path:  /content/student.csv

# Add new columns: Create "Total_Marks" (sum of the three subjects) and "Average" (Total_Marks divided by 3).
df["total_marks"]=df["maths"]+df["science"]+df["english"]
df["average"]=df["total_marks"]/3
print("added total marks and average marks \n",df)

# Handle missing values: Introduce a NaN in the "Science" column, identify it using isnull(), and replace it with the column mean using fillna().
df.loc[2,"science"]=None
print(df.isnull())
print(df.fillna(df["science"].mean()))

# Filter data: Display all students whose "Average" score is greater than 75.
gr_avg=df[df["average"]>75]
print(gr_avg)

# Sort data: Sort the DataFrame by "Total_Marks" in descending order and show the top 3 performers.
sort3=df.sort_values(by="total_marks",ascending=False)
print(sort3.head(3))

# Group data: Group students based on their "English" score range (e.g., above or below 70) and find the mean of "Maths" and "Science" marks for each group.
group_eng=df.groupby("student_name")["english">=70]
print(group_eng)

# Merge DataFrames: Combine one DataFrame containing "Student_Name" and "Total_Marks" with another containing "Student_Name" and "Sports_Score"; create a new "Overall_Score" column by summing both.
std_mrks=pd.DataFrame({
    "student_name":["A","B","C","D","E"],
    "total_marks":[10,20,30,40,50]
})
std_sports=pd.DataFrame({
    "student_name":["A","B","C","D","E"],
    "sports_score":[10,20,30,40,50]
})
new_df=pd.merge(std_mrks,std_sports,on="student_name")
print(new_df)

# Export data: Use the os library to export the final DataFrame to a CSV file on your Desktop and verify its creation using os.path.exists().
import os
user_name=os.getlogin()
df.to_csv("C:\Users\rutur\OneDrive\Desktop\student.csv", index=False)
if os.path.exists("C:\Users\rutur\OneDrive\Desktop\student.csv"):
  print("data exported successfuly")
else:
  print("file not found")